//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GithubProcessor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GithubProcessor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aardvark
        ///aardvarks
        ///aardwolf
        ///ab
        ///abac
        ///abaca
        ///aback
        ///abacterial
        ///abactinal
        ///abacus
        ///abacuses
        ///abadan
        ///abaddon
        ///abaft
        ///abakan
        ///abalone
        ///abalones
        ///abamp
        ///abampere
        ///abandon
        ///abandoned
        ///abandonee
        ///abandoner
        ///abandoning
        ///abandonment
        ///abandonments
        ///abandons
        ///abase
        ///abased
        ///abasement
        ///abasements
        ///abaser
        ///abases
        ///abash
        ///abashed
        ///abashes
        ///abashing
        ///abashment
        ///abasing
        ///abate
        ///abated
        ///abatement
        ///abatements
        ///abater
        ///abates
        ///abating
        ///abatis
        ///abatises
        ///abator
        ///abattoir
        ///abaxial
        ///abbacy
        ///abbas
        ///abbasid
        ///abbatial
        ///abbe
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnglishWords {
            get {
                return ResourceManager.GetString("EnglishWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a&apos;s
        ///able
        ///about
        ///above
        ///according
        ///accordingly
        ///across
        ///actually
        ///after
        ///afterwards
        ///again
        ///against
        ///ain&apos;t
        ///all
        ///allow
        ///allows
        ///almost
        ///alone
        ///along
        ///already
        ///also
        ///although
        ///always
        ///am
        ///among
        ///amongst
        ///an
        ///and
        ///another
        ///any
        ///anybody
        ///anyhow
        ///anyone
        ///anything
        ///anyway
        ///anyways
        ///anywhere
        ///apart
        ///appear
        ///appreciate
        ///appropriate
        ///are
        ///aren&apos;t
        ///around
        ///as
        ///aside
        ///ask
        ///asking
        ///associated
        ///at
        ///available
        ///away
        ///awfully
        ///be
        ///became
        ///because
        ///become
        ///becomes
        ///becoming
        ///been
        ///before
        ///beforehand
        ///behind
        ///being
        ///believe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StopWords {
            get {
                return ResourceManager.GetString("StopWords", resourceCulture);
            }
        }
    }
}
